apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: 881307377501.dkr.ecr.us-east-2.amazonaws.com/cormus:d2f131fca0afad54fa9e73a7fdc0f9f086675bc4
        #imagePullPolicy: Never # Alterado para Never para utilizar a imagem local
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: DATABASE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DATABASE_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080